version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: ratings-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: review-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: adminuser
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d review-service"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg_data:
